spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.64.2:3306/litbubble
    username: root
    password: qwertyuiop
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate.naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
